tap "jandedobbeleer/oh-my-posh"
tap "terraform-linters/tap"

# CLI tools
brew "age"
brew "bat"
brew "direnv"
brew "bash-language-server"
brew "e1s"
brew "eza"
brew "ffmpeg"
brew "fzf"
brew "gopls"
brew "marksman"
brew "mise"
brew "neovim"
brew "pre-commit"
brew "shellcheck"
brew "sops"
brew "terraform-ls"
brew "tldr"
brew "wget"
brew "zoxide"
brew "zsh-autosuggestions"
brew "zsh-syntax-highlighting"
brew "jandedobbeleer/oh-my-posh/oh-my-posh"

# Apps
cask "tflint"
cask "bluesnooze"
cask "karabiner-elements"
cask "rectangle"
cask "zed"
